### ISSUE TITLE
Please fix the repository description URL

### ISSUE THREAD

**Issue by jankeromnes** [potigol/gitpod#1]
👋 Hello!

Really cool project! 👍 I just noticed that the URL in your repository description is broken:

> https://gitpod.io/#https://gihub.com/potigol/replit

It uses `gihub.com` instead of `github.com`. Trying to open it shows this Gitpod error:

> Error: context is not defined

Please add the missing `t` in `github.com`.

**Comment by lrlucena** [comment]
Thank you.
